name = "openf1-car-telemetry"
main = "src/index.ts"
compatibility_date = "2026-02-08"


[[d1_databases]]
binding = "DB"
database_name = "openf1-car-telemetry"
database_id = "76d6106c-c187-4745-8dd4-e379212148c3"

[[r2_buckets]]
binding = "CAR_TELEMETRY_BUCKET"
bucket_name = "openf1-car-telemetry-cache"
